### ISSUE TITLE
npm run failed

### ISSUE THREAD

**Issue by sinkcup** [lint-md/cli#11]
重现步骤：

1. install

```
npm i --save-dev @lint-md/cli
```

2. `package.json`

```
{
  "scripts": {
    "lint": "lint-md docs/"
  }
}
```

3. run

```
npm run lint
```

结果：

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './lint'
Require stack:
- ./node_modules/@lint-md/cli/lib/lint-md.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
```

**Comment by sinkcup** [comment]
build 出来的目录是大写的 Lint 和 Fix，导致问题。

```
ls -l ./node_modules/@lint-md/cli/lib/ | awk {'print $9'}

Fix
Lint
helper
index.d.ts
index.js
index.js.map
lint-md.d.ts
lint-md.js
lint-md.js.map
types.d.ts
types.js
types.js.map
```

```
cd ./node_modules/@lint-md/cli/lib/
mv Lint lint
mv Fix fix
node ./lint-md.js
```

**Comment by sinkcup** [comment]
我在 mac 区分大小写的磁盘卷 上构建的目录是小写的，为什么 npm 里下载的目录是大写的？奇怪。

<img width="858" alt="image" src="https://user-images.githubusercontent.com/4971414/159116057-419b1d05-02dc-4109-ae41-d6f8ce99505f.png">

**Comment by yuzhanglong** [comment]
谢谢你的 issue！
我刚刚重新跑了一下，没有复现你这个问题，不过按照道理来说大小写不区分确实不太合理，具体原因我也不清楚。
目前我已经重新构建并发包。

**Comment by yuzhanglong** [comment]
查了下资料，正如你在 issue 提到的，应该是 MacOS 默认磁盘分区不区分大小写导致了这个问题。感谢！

**Comment by sinkcup** [comment]
那就好。建议新增一个区分大小写的 macOS 卷宗用于存放代码，参考 https://segmentfault.com/a/1190000038938026
