### ISSUE TITLE
安全隐患：依赖扫描发现漏洞

### ISSUE THREAD

**Issue by shaunthegeek** [lint-md/cli#14]
```
yarn audit
```

<img width="785" alt="image" src="https://user-images.githubusercontent.com/4971414/163113602-426682e0-4673-4ce6-a526-acec5e77f1cf.png">

```
npm audit
```

```
# npm audit report

minimist  <1.2.6
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix`
node_modules/minimist

trim  <0.0.3
Severity: high
Regular Expression Denial of Service in trim - https://github.com/advisories/GHSA-w5p7-h5w8-2hfq
No fix available
node_modules/trim
  remark-parse  <=8.0.3
  Depends on vulnerable versions of trim
  node_modules/remark-parse
    @lint-md/core  *
    Depends on vulnerable versions of remark-parse
    node_modules/@lint-md/core

4 vulnerabilities (3 high, 1 critical)
```

**Comment by yuzhanglong** [comment]
收到

**Comment by luojiyin1987** [comment]
https://www.npmjs.com/package/remark-parse-no-trim  
这个包是否有帮助？  
"remark-parse": "^6.0.2"     版本挺旧的，  是否依赖特定的api ？

**Comment by yuzhanglong** [comment]
正在迁移中

**Comment by yuzhanglong** [comment]
由于近几个月忙于秋招无暇维护 😭，实在抱歉，感谢等待这么长时间~
现在你可以使用最新版的 lint-md CLI 工具,目前处于 beta 状态，欢迎试用：https://github.com/lint-md/lint-md#lint-markdown-20-beta 
主要的变动有：
1. 重构文本修复算法，fix 能力性能提升上百倍。
2. 支持多线程运行。
3. 底层 Markdown 解析库 remark 迁移至最新版。
4. 体验更好的命令行输出提示。
5. 项目架构完全重构，代码质量大幅提升，更方便 contribute😄

bug 或建议欢迎到 https://github.com/lint-md/lint-md/issues 提出。
