### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by ripperhe** [lint-md/cli#5]
```
➜ npm i -g @lint-md/cli


npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.

changed 63 packages, and audited 64 packages in 28s

24 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

**Comment by yuzhanglong** [comment]
> ```
> ➜ npm i -g @lint-md/cli
> 
> 
> npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
> 
> changed 63 packages, and audited 64 packages in 28s
> 
> 24 packages are looking for funding
>   run `npm fund` for details
> 
> 4 high severity vulnerabilities
> 
> To address all issues, run:
>   npm audit fix
> 
> Run `npm audit` for details.
> ```

刚刚试了下，这是个 warning，能正常安装。应该是本项目某个第三方库的依赖 bug。
