### ISSUE TITLE
Error 没有停止 github action 的 ci

### ISSUE THREAD

**Issue by yinzixie** [lint-md/cli#6]
是不是没有exit(1)? 都 error了 job 还是继续了。还有希望能够提供 有 warning 也会 exit 的 一个功能。
![image](https://user-images.githubusercontent.com/48106713/140631681-62f870fd-04e1-41a7-90e9-c4f5dfefb84a.png)

**Comment by yuzhanglong** [comment]
@yinzixie 这个问题已经在 v0.1.6 修复，cc @hustcc
